export const types = {
  GET_SINGLE_PROJECT_BEGIN: 'GET_SINGLE_PROJECT_BEGIN',
  GET_SINGLE_PROJECT_SUCCESS: 'GET_SINGLE_PROJECT_SUCCESS',
  GET_SINGLE_PROJECT_ERROR: 'GET_SINGLE_PROJECT_ERROR',
  CREATE_PROJECT_BEGIN: 'CREATE_PROJECT_BEGIN',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_ERROR: 'CREATE_PROJECT_ERROR',
}
