export const types = {
  GET_TASKS_BEGIN: 'GET_TASKS_BEGIN',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',
  ADD_TASK_BEGIN: 'ADD_TASK_BEGIN',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_ERROR: 'ADD_TASK_ERROR',
  REMOVE_TASK_BEGIN: 'REMOVE_TASK_BEGIN',
  REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
  REMOVE_TASK_ERROR: 'REMOVE_TASK_ERROR',
}
