export const types = {
  GET_PREFERENCES_BEGIN: 'GET_PREFERENCES_BEGIN',
  GET_PREFERENCES_SUCCESS: 'GET_PREFERENCES_SUCCESS',
  GET_PREFERENCES_ERROR: 'GET_PREFERENCES_ERROR',
  GET_LABELS_AND_PROJECTS_BEGIN: 'GET_LABELS_AND_PROJECTS_BEGIN',
  GET_LABELS_AND_PROJECTS_SUCCESS: 'GET_LABELS_AND_PROJECTS_SUCCESS',
  GET_LABELS_AND_PROJECTS_ERROR: 'GET_LABELS_AND_PROJECTS_ERROR',
  ADD_LABEL_BEGIN: 'ADD_LABEL_BEGIN',
  ADD_LABEL_SUCCESS: 'ADD_LABEL_SUCCESS',
  ADD_LABEL_ERROR: 'ADD_LABEL_ERROR',
  EDIT_LABEL_BEGIN: 'EDIT_LABEL_BEGIN',
  EDIT_LABEL_SUCCESS: 'EDIT_LABEL_SUCCESS',
  EDIT_LABEL_ERROR: 'EDIT_LABEL_ERROR',
}
