export const types = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_ADD_TASK_MODAL: 'TOGGLE_ADD_TASK_MODAL',
  TOGGLE_MANAGE_LABELS_MODAL: 'TOGGLE_MANAGE_LABELS_MODAL',
  UPDATE_UPLOAD_LIST: 'UPDATE_UPLOAD_LIST',
  CLEAR_FINISHED_UPLOADS: 'CLEAR_FINISHED_UPLOADS',
}
